### PR TITLE
First contact with C API

### PR DESCRIPTION
**Pull request by vvanders**
So, I finally have first contact between Rust and C at the socket level. Right now I've got connect/challenge/response working in unit-test format.

There's still a ton of stuff left to sort out:
-Sending the keep-alive so we formally establish a connection.
-Replay attack mitigation.
-Host connect token address validation.

Also, couple things that would make Rust integration easier but wanted to run by you before I put up a PR:
-Do you have objections to adding const to a couple functions? Right now auto-gen bindings yell at me about mutability differences for things like address strings that are passed in.
-libsodium-sys links sodium via libsodium.so/sodium.lib. Would it be okay to rename sodium-release.lib to sodium.lib and leave sodium-debug.lib as-is? It would mean that users who want to build rust on Windows could skip the env var setup step.

Anyway, let me know what you think. I'm hoping to have the keep alive and real payloads working between them both soon.

### CODE REVIEW

**Comment by gafferongames** [comment]
Sounds great. I can't add const to C because it's not supported in all versions, only more recent ones. C++ is the language that has const.

cheers

- Glenn

**Comment by gafferongames** [comment]
I'm OK with the sodium change, as long as it's fixed up in the reference C impl as well (eg. premake5.lua)

**Comment by gafferongames** [comment]
Looks like this broke the build. I'm not 100% sure, but I think that travis doesn't like it when you try to use sockets in tests, even when they're loopback.

**Comment by vvanders** [comment]
Hmm, that's odd. I haven't had any issue with loopback sockets on travsi.ci(in fact mio uses them as well, but non-blocking stuff can cause some issues).

I'll disable it for now and see how hard it would be to expose the network simulator.

**Comment by gafferongames** [comment]
I mean it would be ideal if we could do actual socket tests between C and Rust as part of our tests, maybe work out why it's failing? I'm just mentioning this because I've noticed problems with previous tests (non-blocking) in yojimbo where the sockets didn't seem to work, or at least, that's what SEEMED to be going on

**Pull request merged**
