### PR TITLE
Build break fix and some small doc updates

### PR DESCRIPTION
**Pull request by vvanders**
Just some quick updates and an API fix, still have a couple more things I want to do before I think we're good on the docs.

### CODE REVIEW

**Comment by gafferongames** [comment]
Thanks! I made small changes to the C API so the sequence # is available to the user for the next payload packet. It occurs to me that the way I did it in C is not threadsafe, so maybe you want to implement a different style interface for Rust, maybe an atomic to get next packet sequence #, and then you pass that sequence number in with the next call to send packet? I don't know.

**Comment by vvanders** [comment]
Rust should be fine, all the sequencing is internal to the server and the type system require that all access is single-threaded. My thoughts on multi-threading is that if someone really wants to do it they can put dispatching in front of the server(there's some really good spmc/mpsc stuff in Rust).

I wanted to use mio to do a bit more threading stuff, however I couldn't find a way to cleanly listen on 0.0.0.0:<port> and still bind connected sockets on 0.0.0.0:<port> without the listening socket grabbing the message first anyway. I'm sure it's something we can retrofit but I'd rather get something out there first that's correct.

**Comment by gafferongames** [comment]
That makes sense, so have Rust running on one thread, with queues for packets in and out? - makes sense.

**Comment by gafferongames** [comment]
Sounds reasonable to me.

**Comment by vvanders** [comment]
Yup, and if you structure it right Rust will even do move semantics so you don't have extra copying happening at the thread boundaries.

**Comment by gafferongames** [comment]
That's fairly impressive and difficult to do in C

**Pull request merged**
